[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lumache"
authors = [{name = "Dias", email = "dias.31407@gmail.com"}]
dynamic = ["version", "description"]